---
- name: Install php-fpm
  apt: pkg={{item}} state=installed
  with_items:
    - php5
    - php5-fpm
    - php5-dev
    - php5-mysql
    - php5-mcrypt
    - php5-mhash
    - php5-xmlrpc
    - php5-mcrypt
    - php5-curl
    - php5-apcu
    - php5-imagick
    - php5-memcached
    - php5-gd
  notify:
      - restart php5-fpm
