---
  - hosts: all

    vars:
      delete_default_vhost: false
      user: www-data
      worker_processes: 2
      pid: /var/run/nginx.pid
      worker_connections: 768
      fpm_port: 9000
      server_name: my.domain.com
      document_root: /var/www/html1

    tasks:
      - include: tasks/setup-nginx.yml

    handlers:
      - include: handlers/handlers.yml
