---
- name: Install mysql
  apt: pkg={{item}} state=installed
  with_items:
    - mysql-server-5.6
    - mysql-client-5.6
  notify:
      - restart mysql
- name: write my.cnf
  action: template src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify:
      - restart nginx
