---

- name: Bootstrap lamp
  hosts: all
  user: ec2-user
  sudo: yes

  vars:
        delete_default_vhost: false
        user: www-data
        worker_processes: 2
        pid: /var/run/nginx.pid
        worker_connections: 768
        fpm_port: 9200
        server_name: my.domain.com
        document_root: /var/www/html
        name: www
        user: www-data
        group: www-data
        listen_allowed_clients: 127.0.0.1
        pm_type: dynamic
        pm_max_children: 5
        pm_start_servers: 2
        pm_min_spare_servers: 1
        pm_max_spare_servers: 3
        pm_process_idle_timeout: 10s
        pm_max_requests: 500
        php_flag: ~
        php_admin_flag: ~
        php_admin_value: ~
  roles:
    - nginx
    - php5


